import {
  AIModelMetadata,
  ModelCapabilityTag,
  ModelCatalogCategory,
  ModelLifecycleStatus,
  ProviderTransport,
} from '../types';
import {
  CanonicalProviderRegistryId,
  getProviderRegistryEntryRequired,
} from '../providers/providerRegistry';

/**
 * Canonical model registry
 * --------------------------------------------------------------------------
 * This file is the source of truth for:
 * - user-facing model ordering,
 * - execution-time canonical model IDs,
 * - tool compatibility,
 * - provider runtime metadata,
 * - legacy alias normalization.
 *
 * Future agents should add or change models here first, then let the derived
 * UI/back-compat helpers flow outward from this registry.
 */

type CanonicalModelDefinition = {
  id: string;
  displayName: string;
  provider: AIModelMetadata['provider'];
  providerId: CanonicalProviderRegistryId;
  family: string;
  modelId: string;
  modelCategory: ModelCatalogCategory;
  capabilityTags: ModelCapabilityTag[];
  transport: ProviderTransport;
  description: string;
  speedRating: number;
  costRating: number;
  contextSize: string;
  status: AIModelMetadata['status'];
  lifecycleStatus: ModelLifecycleStatus;
  isEnabled: boolean;
  isVisibleToUsers: boolean;
  category: AIModelMetadata['category'];
  sortOrder: number;
  supportedTools: string[];
  tags: string[];
  badge?: string;
  isFallback?: boolean;
  capabilities: AIModelMetadata['capabilities'];
  supportsVision: boolean;
  supportsStreaming: boolean;
  envKeyName: string;
  envRequirements: string[];
  baseUrlResolver: string;
  regionSupport: string[];
  supportedRegions?: string[];
  adminNotes?: string;
  legacyAliases?: string[];
};

const SHARED_TEXT_TOOLS = ['chat', 'analyze', 'quiz', 'infographic', 'study', 'image'] as const;
const SHARED_QWEN_REGIONS = ['us-virginia', 'singapore', 'china-mainland', 'hong-kong', 'frankfurt'] as const;

const CANONICAL_MODEL_DEFINITIONS: CanonicalModelDefinition[] = [
  {
    id: 'gemini-3-flash-preview',
    displayName: 'Gemini Flash',
    provider: 'google',
    providerId: 'google-gemini-api',
    family: 'gemini',
    modelId: 'gemini-3-flash-preview',
    modelCategory: 'text',
    capabilityTags: ['text', 'chat', 'reasoning', 'summarization', 'vision', 'ocr', 'multimodal-analysis', 'translation', 'long-context'],
    transport: 'google-genai-native',
    description: 'Fast, balanced Gemini model for the main text, quiz, and analysis workflows.',
    speedRating: 5,
    costRating: 2,
    contextSize: '1M tokens',
    status: 'active',
    lifecycleStatus: 'active',
    isEnabled: true,
    isVisibleToUsers: true,
    category: 'Balanced',
    sortOrder: 10,
    supportedTools: [...SHARED_TEXT_TOOLS],
    tags: ['Gemini', 'Flash', 'Text'],
    badge: 'Fast',
    isFallback: true,
    capabilities: {
      text: true,
      quiz: true,
      documentAnalysis: true,
      infographic: true,
      imageGeneration: false,
      imageEditing: false,
      videoGeneration: false,
      audioGeneration: false,
      speechRecognition: false,
      translation: true,
      ocr: true,
      vision: true,
      reasoning: true,
      longContext: true,
      realtime: false,
      streaming: true,
      thinking: true,
    },
    supportsVision: true,
    supportsStreaming: true,
    envKeyName: 'GEMINI_API_KEY',
    envRequirements: ['GEMINI_API_KEY'],
    baseUrlResolver: 'google-sdk-generate-content',
    regionSupport: ['global'],
    supportedRegions: ['global'],
    adminNotes: 'Default premium text model. Keep first in compatible selector ordering.',
    legacyAliases: ['gemini-3.1-flash-lite-preview'],
  },
  {
    id: 'qwen3.5-plus',
    displayName: 'Qwen 3.5 Plus',
    provider: 'qwen',
    providerId: 'alibaba-model-studio/qwen',
    family: 'qwen3.5',
    modelId: 'qwen3.5-plus',
    modelCategory: 'text',
    capabilityTags: ['text', 'chat', 'reasoning', 'summarization', 'long-context'],
    transport: 'alibaba-openai-compatible',
    description: 'High-context Qwen reasoning model for text-heavy tools through DashScope compatible mode.',
    speedRating: 4,
    costRating: 3,
    contextSize: '1M tokens',
    status: 'active',
    lifecycleStatus: 'active',
    isEnabled: true,
    isVisibleToUsers: true,
    category: 'Advanced',
    sortOrder: 20,
    supportedTools: [...SHARED_TEXT_TOOLS],
    tags: ['Qwen', 'Reasoning', 'Text'],
    badge: 'Plus',
    isFallback: true,
    capabilities: {
      text: true,
      quiz: true,
      documentAnalysis: true,
      infographic: true,
      imageGeneration: false,
      imageEditing: false,
      videoGeneration: false,
      audioGeneration: false,
      speechRecognition: false,
      translation: false,
      ocr: false,
      vision: false,
      reasoning: true,
      longContext: true,
      realtime: false,
      streaming: true,
      thinking: true,
    },
    supportsVision: false,
    supportsStreaming: true,
    envKeyName: 'DASHSCOPE_API_KEY',
    envRequirements: ['DASHSCOPE_API_KEY', 'ALIBABA_MODEL_STUDIO_REGION', 'ALIBABA_MODEL_STUDIO_BASE_URL'],
    baseUrlResolver: 'dashscope-compatible-chat',
    regionSupport: [...SHARED_QWEN_REGIONS],
    supportedRegions: [...SHARED_QWEN_REGIONS],
    adminNotes: 'Primary Qwen text model. Keep second after Gemini Flash for compatible tools.',
    legacyAliases: ['qwen3.5-plus-2026-02-15'],
  },
  {
    id: 'gemini-3-pro-preview',
    displayName: 'Gemini Pro',
    provider: 'google',
    providerId: 'google-gemini-api',
    family: 'gemini',
    modelId: 'gemini-3-pro-preview',
    modelCategory: 'text',
    capabilityTags: ['text', 'chat', 'reasoning', 'summarization', 'vision', 'ocr', 'multimodal-analysis', 'translation', 'long-context'],
    transport: 'google-genai-native',
    description: 'Higher-capability Gemini model for deeper reasoning and advanced educational outputs.',
    speedRating: 3,
    costRating: 4,
    contextSize: '2M tokens',
    status: 'preview',
    lifecycleStatus: 'experimental',
    isEnabled: true,
    isVisibleToUsers: true,
    category: 'Advanced',
    sortOrder: 30,
    supportedTools: [...SHARED_TEXT_TOOLS],
    tags: ['Gemini', 'Pro', 'Reasoning'],
    badge: 'Flagship',
    capabilities: {
      text: true,
      quiz: true,
      documentAnalysis: true,
      infographic: true,
      imageGeneration: false,
      imageEditing: false,
      videoGeneration: false,
      audioGeneration: false,
      speechRecognition: false,
      translation: true,
      ocr: true,
      vision: true,
      reasoning: true,
      longContext: true,
      realtime: false,
      streaming: true,
      thinking: true,
    },
    supportsVision: true,
    supportsStreaming: true,
    envKeyName: 'GEMINI_API_KEY',
    envRequirements: ['GEMINI_API_KEY'],
    baseUrlResolver: 'google-sdk-generate-content',
    regionSupport: ['global'],
    supportedRegions: ['global'],
    adminNotes: 'Official preview model. Legacy persisted id gemini-3.1-pro-preview should map here.',
    legacyAliases: ['gemini-3.1-pro-preview'],
  },
  {
    id: 'qwen-plus',
    displayName: 'Qwen Plus',
    provider: 'qwen',
    providerId: 'alibaba-model-studio/qwen',
    family: 'qwen3',
    modelId: 'qwen-plus',
    modelCategory: 'text',
    capabilityTags: ['text', 'chat', 'reasoning', 'summarization', 'long-context'],
    transport: 'alibaba-openai-compatible',
    description: 'Stable Qwen text model for explicit same-provider fallback and broader compatibility.',
    speedRating: 4,
    costRating: 2,
    contextSize: '995K tokens',
    status: 'active',
    lifecycleStatus: 'active',
    isEnabled: true,
    isVisibleToUsers: true,
    category: 'Balanced',
    sortOrder: 40,
    supportedTools: [...SHARED_TEXT_TOOLS],
    tags: ['Qwen', 'Stable', 'Text'],
    badge: 'Stable',
    capabilities: {
      text: true,
      quiz: true,
      documentAnalysis: true,
      infographic: true,
      imageGeneration: false,
      imageEditing: false,
      videoGeneration: false,
      audioGeneration: false,
      speechRecognition: false,
      translation: false,
      ocr: false,
      vision: false,
      reasoning: true,
      longContext: true,
      realtime: false,
      streaming: true,
      thinking: true,
    },
    supportsVision: false,
    supportsStreaming: true,
    envKeyName: 'DASHSCOPE_API_KEY',
    envRequirements: ['DASHSCOPE_API_KEY', 'ALIBABA_MODEL_STUDIO_REGION', 'ALIBABA_MODEL_STUDIO_BASE_URL'],
    baseUrlResolver: 'dashscope-compatible-chat',
    regionSupport: [...SHARED_QWEN_REGIONS],
    supportedRegions: [...SHARED_QWEN_REGIONS],
    adminNotes: 'Stable same-family fallback option for Qwen text routing.',
    legacyAliases: [
      'qwen-plus-latest',
      'qwen-plus-2025-12-01',
      'qwen-plus-2025-09-11',
      'qwen-plus-2025-07-28',
      'qwen-plus-2025-01-25',
    ],
  },
  {
    id: 'qwen3-vl-plus',
    displayName: 'Qwen VL Plus',
    provider: 'qwen',
    providerId: 'alibaba-model-studio/qwen-vl',
    family: 'qwen-vl',
    modelId: 'qwen3-vl-plus',
    modelCategory: 'multimodal-analysis',
    capabilityTags: ['vision', 'ocr', 'multimodal-analysis', 'reasoning', 'text', 'chat'],
    transport: 'alibaba-openai-compatible',
    description: 'Vision-capable Qwen model for OCR-aware analysis and infographic support.',
    speedRating: 4,
    costRating: 3,
    contextSize: 'Varies',
    status: 'active',
    lifecycleStatus: 'active',
    isEnabled: true,
    isVisibleToUsers: true,
    category: 'Balanced',
    sortOrder: 50,
    supportedTools: ['analyze', 'infographic', 'study'],
    tags: ['Qwen', 'Vision', 'OCR'],
    badge: 'Vision',
    capabilities: {
      text: true,
      quiz: false,
      documentAnalysis: true,
      infographic: true,
      imageGeneration: false,
      imageEditing: false,
      videoGeneration: false,
      audioGeneration: false,
      speechRecognition: false,
      translation: false,
      ocr: true,
      vision: true,
      reasoning: true,
      longContext: false,
      realtime: false,
      streaming: true,
      thinking: false,
    },
    supportsVision: true,
    supportsStreaming: true,
    envKeyName: 'DASHSCOPE_API_KEY',
    envRequirements: ['DASHSCOPE_API_KEY', 'ALIBABA_MODEL_STUDIO_REGION', 'ALIBABA_MODEL_STUDIO_BASE_URL'],
    baseUrlResolver: 'dashscope-compatible-chat',
    regionSupport: [...SHARED_QWEN_REGIONS],
    supportedRegions: [...SHARED_QWEN_REGIONS],
    adminNotes: 'Use only through compatible-mode chat/completions with multimodal message parts.',
    legacyAliases: ['qwen3-vl-plus-2025-12-19', 'qwen-vl-ocr', 'qwen-vl-ocr-2025-11-20'],
  },
  {
    id: 'qwen3-vl-flash',
    displayName: 'Qwen VL Flash',
    provider: 'qwen',
    providerId: 'alibaba-model-studio/qwen-vl',
    family: 'qwen-vl',
    modelId: 'qwen3-vl-flash',
    modelCategory: 'multimodal-analysis',
    capabilityTags: ['vision', 'ocr', 'multimodal-analysis', 'reasoning', 'text', 'chat'],
    transport: 'alibaba-openai-compatible',
    description: 'Faster Qwen vision model for OCR-rich analysis where lower latency matters.',
    speedRating: 5,
    costRating: 2,
    contextSize: 'Varies',
    status: 'active',
    lifecycleStatus: 'active',
    isEnabled: true,
    isVisibleToUsers: true,
    category: 'Balanced',
    sortOrder: 60,
    supportedTools: ['analyze', 'infographic', 'study'],
    tags: ['Qwen', 'Vision', 'Fast'],
    badge: 'Vision',
    capabilities: {
      text: true,
      quiz: false,
      documentAnalysis: true,
      infographic: true,
      imageGeneration: false,
      imageEditing: false,
      videoGeneration: false,
      audioGeneration: false,
      speechRecognition: false,
      translation: false,
      ocr: true,
      vision: true,
      reasoning: true,
      longContext: false,
      realtime: false,
      streaming: true,
      thinking: false,
    },
    supportsVision: true,
    supportsStreaming: true,
    envKeyName: 'DASHSCOPE_API_KEY',
    envRequirements: ['DASHSCOPE_API_KEY', 'ALIBABA_MODEL_STUDIO_REGION', 'ALIBABA_MODEL_STUDIO_BASE_URL'],
    baseUrlResolver: 'dashscope-compatible-chat',
    regionSupport: [...SHARED_QWEN_REGIONS],
    supportedRegions: [...SHARED_QWEN_REGIONS],
    adminNotes: 'Fast OCR/vision option. Legacy US-specific aliases should canonicalize here.',
    legacyAliases: ['qwen3-vl-flash-2026-01-22-us', 'qwen3-vl-flash-us'],
  },
  {
    id: 'gemini-2.5-flash-image',
    displayName: 'Gemini Flash Image',
    provider: 'google',
    providerId: 'google-gemini-api',
    family: 'gemini-image',
    modelId: 'gemini-2.5-flash-image',
    modelCategory: 'image-generation',
    capabilityTags: ['image-generation', 'image-editing'],
    transport: 'google-genai-native',
    description: 'Fast official Gemini image model for image generation and infographic visuals.',
    speedRating: 4,
    costRating: 2,
    contextSize: 'N/A',
    status: 'active',
    lifecycleStatus: 'active',
    isEnabled: true,
    isVisibleToUsers: true,
    category: 'Balanced',
    sortOrder: 70,
    supportedTools: ['image-generator', 'image-editor'],
    tags: ['Gemini', 'Image', 'Creative'],
    badge: 'Image',
    capabilities: {
      text: false,
      quiz: false,
      documentAnalysis: false,
      infographic: false,
      imageGeneration: true,
      imageEditing: true,
      videoGeneration: false,
      audioGeneration: false,
      speechRecognition: false,
      translation: false,
      ocr: false,
      vision: false,
      reasoning: false,
      longContext: false,
      realtime: false,
      streaming: false,
    },
    supportsVision: false,
    supportsStreaming: false,
    envKeyName: 'GEMINI_API_KEY',
    envRequirements: ['GEMINI_API_KEY'],
    baseUrlResolver: 'google-sdk-generate-content',
    regionSupport: ['global'],
    supportedRegions: ['global'],
    adminNotes: 'Primary verified image-generation model.',
    legacyAliases: ['gemini-3.1-flash-image-preview'],
  },
  {
    id: 'gemini-3-pro-image-preview',
    displayName: 'Gemini Pro Image',
    provider: 'google',
    providerId: 'google-gemini-api',
    family: 'gemini-image',
    modelId: 'gemini-3-pro-image-preview',
    modelCategory: 'image-generation',
    capabilityTags: ['image-generation', 'image-editing'],
    transport: 'google-genai-native',
    description: 'Higher-fidelity Gemini image model for premium generated visuals.',
    speedRating: 3,
    costRating: 4,
    contextSize: 'N/A',
    status: 'preview',
    lifecycleStatus: 'experimental',
    isEnabled: true,
    isVisibleToUsers: true,
    category: 'Advanced',
    sortOrder: 80,
    supportedTools: ['image-generator', 'image-editor'],
    tags: ['Gemini', 'Image', 'Premium'],
    badge: 'Pro Image',
    capabilities: {
      text: false,
      quiz: false,
      documentAnalysis: false,
      infographic: false,
      imageGeneration: true,
      imageEditing: true,
      videoGeneration: false,
      audioGeneration: false,
      speechRecognition: false,
      translation: false,
      ocr: false,
      vision: false,
      reasoning: false,
      longContext: false,
      realtime: false,
      streaming: false,
    },
    supportsVision: false,
    supportsStreaming: false,
    envKeyName: 'GEMINI_API_KEY',
    envRequirements: ['GEMINI_API_KEY'],
    baseUrlResolver: 'google-sdk-generate-content',
    regionSupport: ['global'],
    supportedRegions: ['global'],
    adminNotes: 'Preview image model kept behind explicit canonical ID.',
  },
  {
    id: 'gemini-2.5-flash-native-audio-preview-09-2025',
    displayName: 'Gemini Native Audio',
    provider: 'google',
    providerId: 'google-gemini-api',
    family: 'gemini-audio',
    modelId: 'gemini-2.5-flash-native-audio-preview-09-2025',
    modelCategory: 'audio-understanding',
    capabilityTags: ['audio-understanding', 'asr', 'speech', 'speech-generation', 'realtime', 'translation'],
    transport: 'google-genai-native',
    description: 'Official Gemini native-audio preview model for live voice sessions.',
    speedRating: 5,
    costRating: 3,
    contextSize: 'N/A',
    status: 'preview',
    lifecycleStatus: 'experimental',
    isEnabled: true,
    isVisibleToUsers: true,
    category: 'Advanced',
    sortOrder: 90,
    supportedTools: ['live-voice'],
    tags: ['Gemini', 'Audio', 'Realtime'],
    badge: 'Voice',
    capabilities: {
      text: false,
      quiz: false,
      documentAnalysis: false,
      infographic: false,
      imageGeneration: false,
      imageEditing: false,
      videoGeneration: false,
      audioGeneration: true,
      speechRecognition: true,
      translation: true,
      ocr: false,
      vision: false,
      reasoning: true,
      longContext: false,
      realtime: true,
      streaming: true,
    },
    supportsVision: false,
    supportsStreaming: true,
    envKeyName: 'GEMINI_API_KEY',
    envRequirements: ['GEMINI_API_KEY'],
    baseUrlResolver: 'google-live-api',
    regionSupport: ['global'],
    supportedRegions: ['global'],
    adminNotes: 'Realtime/live-voice model. Keep isolated from regular text routing.',
  },
  {
    id: 'veo-3.1-fast-generate-preview',
    displayName: 'Veo Fast',
    provider: 'google',
    providerId: 'google-veo',
    family: 'veo',
    modelId: 'veo-3.1-fast-generate-preview',
    modelCategory: 'video-generation',
    capabilityTags: ['video-generation', 'text-to-video'],
    transport: 'google-veo-native',
    description: 'Official Veo fast preview model for future real video generation.',
    speedRating: 4,
    costRating: 4,
    contextSize: 'N/A',
    status: 'preview',
    lifecycleStatus: 'experimental',
    isEnabled: true,
    isVisibleToUsers: true,
    category: 'Advanced',
    sortOrder: 100,
    supportedTools: ['video-generator'],
    tags: ['Google', 'Video', 'Preview'],
    badge: 'Video',
    capabilities: {
      text: false,
      quiz: false,
      documentAnalysis: false,
      infographic: false,
      imageGeneration: false,
      imageEditing: false,
      videoGeneration: true,
      audioGeneration: false,
      speechRecognition: false,
      translation: false,
      ocr: false,
      vision: false,
      reasoning: false,
      longContext: false,
      realtime: false,
      streaming: false,
    },
    supportsVision: false,
    supportsStreaming: false,
    envKeyName: 'GEMINI_API_KEY',
    envRequirements: ['GEMINI_API_KEY'],
    baseUrlResolver: 'google-veo-generate',
    regionSupport: ['global'],
    supportedRegions: ['global'],
    adminNotes: 'Kept in preview state until the dedicated backend video adapter is implemented.',
  },
  {
    id: 'veo-3.1-generate-preview',
    displayName: 'Veo Generate',
    provider: 'google',
    providerId: 'google-veo',
    family: 'veo',
    modelId: 'veo-3.1-generate-preview',
    modelCategory: 'video-generation',
    capabilityTags: ['video-generation', 'text-to-video'],
    transport: 'google-veo-native',
    description: 'Higher-quality Veo preview model reserved for future backend video wiring.',
    speedRating: 2,
    costRating: 5,
    contextSize: 'N/A',
    status: 'preview',
    lifecycleStatus: 'experimental',
    isEnabled: true,
    isVisibleToUsers: true,
    category: 'Advanced',
    sortOrder: 110,
    supportedTools: ['video-generator'],
    tags: ['Google', 'Video', 'Premium'],
    badge: 'Video',
    capabilities: {
      text: false,
      quiz: false,
      documentAnalysis: false,
      infographic: false,
      imageGeneration: false,
      imageEditing: false,
      videoGeneration: true,
      audioGeneration: false,
      speechRecognition: false,
      translation: false,
      ocr: false,
      vision: false,
      reasoning: false,
      longContext: false,
      realtime: false,
      streaming: false,
    },
    supportsVision: false,
    supportsStreaming: false,
    envKeyName: 'GEMINI_API_KEY',
    envRequirements: ['GEMINI_API_KEY'],
    baseUrlResolver: 'google-veo-generate',
    regionSupport: ['global'],
    supportedRegions: ['global'],
    adminNotes: 'Preview-only until the real video route exists.',
  },
  {
    id: 'imagen-4.0-generate-001',
    displayName: 'Imagen 4',
    provider: 'google',
    providerId: 'google-imagen',
    family: 'imagen',
    modelId: 'imagen-4.0-generate-001',
    modelCategory: 'image-generation',
    capabilityTags: ['image-generation'],
    transport: 'google-imagen-native',
    description: 'Prepared internal catalog entry for future dedicated Imagen activation.',
    speedRating: 4,
    costRating: 3,
    contextSize: 'N/A',
    status: 'disabled',
    lifecycleStatus: 'planned',
    isEnabled: false,
    isVisibleToUsers: false,
    category: 'Advanced',
    sortOrder: 120,
    supportedTools: ['image-generator'],
    tags: ['Google', 'Imagen', 'Hidden'],
    capabilities: {
      text: false,
      quiz: false,
      documentAnalysis: false,
      infographic: false,
      imageGeneration: true,
      imageEditing: false,
      videoGeneration: false,
      audioGeneration: false,
      speechRecognition: false,
      translation: false,
      ocr: false,
      vision: false,
      reasoning: false,
      longContext: false,
      realtime: false,
      streaming: false,
    },
    supportsVision: false,
    supportsStreaming: false,
    envKeyName: 'GEMINI_API_KEY',
    envRequirements: ['GEMINI_API_KEY'],
    baseUrlResolver: 'google-imagen-generate',
    regionSupport: ['global'],
    supportedRegions: ['global'],
    adminNotes: 'Hidden until Imagen-specific adapter and validation are enabled.',
  },
  {
    id: 'wan2.6-t2i',
    displayName: 'Wan T2I',
    provider: 'qwen',
    providerId: 'alibaba-model-studio/wan',
    family: 'wan2.6',
    modelId: 'wan2.6-t2i',
    modelCategory: 'image-generation',
    capabilityTags: ['image-generation'],
    transport: 'alibaba-native-media',
    description: 'Prepared internal catalog entry for future Alibaba Wan text-to-image activation.',
    speedRating: 3,
    costRating: 3,
    contextSize: 'N/A',
    status: 'disabled',
    lifecycleStatus: 'planned',
    isEnabled: false,
    isVisibleToUsers: false,
    category: 'Advanced',
    sortOrder: 130,
    supportedTools: ['image-generator'],
    tags: ['Alibaba', 'Wan', 'Hidden'],
    capabilities: {
      text: false,
      quiz: false,
      documentAnalysis: false,
      infographic: false,
      imageGeneration: true,
      imageEditing: false,
      videoGeneration: false,
      audioGeneration: false,
      speechRecognition: false,
      translation: false,
      ocr: false,
      vision: false,
      reasoning: false,
      longContext: false,
      realtime: false,
      streaming: false,
    },
    supportsVision: false,
    supportsStreaming: false,
    envKeyName: 'DASHSCOPE_API_KEY',
    envRequirements: ['DASHSCOPE_API_KEY', 'ALIBABA_MODEL_STUDIO_REGION', 'ALIBABA_MODEL_STUDIO_BASE_URL'],
    baseUrlResolver: 'alibaba-native-media',
    regionSupport: [...SHARED_QWEN_REGIONS],
    supportedRegions: [...SHARED_QWEN_REGIONS],
    adminNotes: 'Hidden until Wan text-to-image execution is validated in this environment.',
  },
  {
    id: 'wan2.6-image',
    displayName: 'Wan Image Edit',
    provider: 'qwen',
    providerId: 'alibaba-model-studio/wan',
    family: 'wan2.6',
    modelId: 'wan2.6-image',
    modelCategory: 'image-editing',
    capabilityTags: ['image-editing'],
    transport: 'alibaba-native-media',
    description: 'Prepared internal catalog entry for future Alibaba Wan image-editing activation.',
    speedRating: 3,
    costRating: 4,
    contextSize: 'N/A',
    status: 'disabled',
    lifecycleStatus: 'planned',
    isEnabled: false,
    isVisibleToUsers: false,
    category: 'Advanced',
    sortOrder: 140,
    supportedTools: ['image-editor'],
    tags: ['Alibaba', 'Wan', 'Hidden'],
    capabilities: {
      text: false,
      quiz: false,
      documentAnalysis: false,
      infographic: false,
      imageGeneration: false,
      imageEditing: true,
      videoGeneration: false,
      audioGeneration: false,
      speechRecognition: false,
      translation: false,
      ocr: false,
      vision: false,
      reasoning: false,
      longContext: false,
      realtime: false,
      streaming: false,
    },
    supportsVision: false,
    supportsStreaming: false,
    envKeyName: 'DASHSCOPE_API_KEY',
    envRequirements: ['DASHSCOPE_API_KEY', 'ALIBABA_MODEL_STUDIO_REGION', 'ALIBABA_MODEL_STUDIO_BASE_URL'],
    baseUrlResolver: 'alibaba-native-media',
    regionSupport: [...SHARED_QWEN_REGIONS],
    supportedRegions: [...SHARED_QWEN_REGIONS],
    adminNotes: 'Hidden until Wan image-editing execution is validated in this environment.',
  },
  {
    id: 'wan2.6-t2v-us',
    displayName: 'Wan T2V US',
    provider: 'qwen',
    providerId: 'alibaba-model-studio/wan',
    family: 'wan2.6',
    modelId: 'wan2.6-t2v-us',
    modelCategory: 'video-generation',
    capabilityTags: ['video-generation', 'text-to-video'],
    transport: 'alibaba-native-media',
    description: 'Prepared internal catalog entry for future Alibaba Wan text-to-video activation.',
    speedRating: 2,
    costRating: 5,
    contextSize: 'N/A',
    status: 'disabled',
    lifecycleStatus: 'planned',
    isEnabled: false,
    isVisibleToUsers: false,
    category: 'Advanced',
    sortOrder: 150,
    supportedTools: ['video-generator'],
    tags: ['Alibaba', 'Wan', 'Hidden'],
    capabilities: {
      text: false,
      quiz: false,
      documentAnalysis: false,
      infographic: false,
      imageGeneration: false,
      imageEditing: false,
      videoGeneration: true,
      audioGeneration: false,
      speechRecognition: false,
      translation: false,
      ocr: false,
      vision: false,
      reasoning: false,
      longContext: false,
      realtime: false,
      streaming: false,
    },
    supportsVision: false,
    supportsStreaming: false,
    envKeyName: 'DASHSCOPE_API_KEY',
    envRequirements: ['DASHSCOPE_API_KEY', 'ALIBABA_MODEL_STUDIO_REGION', 'ALIBABA_MODEL_STUDIO_BASE_URL'],
    baseUrlResolver: 'alibaba-native-media',
    regionSupport: [...SHARED_QWEN_REGIONS],
    supportedRegions: [...SHARED_QWEN_REGIONS],
    adminNotes: 'Hidden until Wan video execution is validated in this environment.',
  },
  {
    id: 'qwen3-asr-flash-us',
    displayName: 'Qwen ASR Flash US',
    provider: 'qwen',
    providerId: 'alibaba-model-studio/audio',
    family: 'qwen-asr',
    modelId: 'qwen3-asr-flash-2025-09-08-us',
    modelCategory: 'audio-understanding',
    capabilityTags: ['audio-understanding', 'asr', 'speech'],
    transport: 'alibaba-native-media',
    description: 'Prepared internal catalog entry for future Alibaba speech recognition activation.',
    speedRating: 4,
    costRating: 2,
    contextSize: 'N/A',
    status: 'disabled',
    lifecycleStatus: 'planned',
    isEnabled: false,
    isVisibleToUsers: false,
    category: 'Balanced',
    sortOrder: 160,
    supportedTools: ['live-voice'],
    tags: ['Alibaba', 'Audio', 'Hidden'],
    capabilities: {
      text: false,
      quiz: false,
      documentAnalysis: false,
      infographic: false,
      imageGeneration: false,
      imageEditing: false,
      videoGeneration: false,
      audioGeneration: true,
      speechRecognition: true,
      translation: false,
      ocr: false,
      vision: false,
      reasoning: false,
      longContext: false,
      realtime: false,
      streaming: false,
    },
    supportsVision: false,
    supportsStreaming: false,
    envKeyName: 'DASHSCOPE_API_KEY',
    envRequirements: ['DASHSCOPE_API_KEY', 'ALIBABA_MODEL_STUDIO_REGION', 'ALIBABA_MODEL_STUDIO_BASE_URL'],
    baseUrlResolver: 'alibaba-native-media',
    regionSupport: [...SHARED_QWEN_REGIONS],
    supportedRegions: [...SHARED_QWEN_REGIONS],
    adminNotes: 'Hidden until Alibaba audio/ASR adapter is implemented and validated.',
  },
];

const buildLegacyMetadata = (model: CanonicalModelDefinition): AIModelMetadata => {
  const providerEntry = getProviderRegistryEntryRequired(model.providerId);

  return {
    id: model.id,
    displayName: model.displayName,
    provider: model.provider,
    providerId: model.providerId,
    family: model.family,
    modelId: model.modelId,
    modelCategory: model.modelCategory,
    capabilityTags: [...model.capabilityTags],
    transport: model.transport,
    description: model.description,
    speedRating: model.speedRating,
    costRating: model.costRating,
    contextSize: model.contextSize,
    status: model.status,
    lifecycleStatus: model.lifecycleStatus,
    tags: model.tags,
    isFallback: model.isFallback,
    isEnabled: model.isEnabled && model.lifecycleStatus !== 'disabled',
    isVisibleToUsers: model.isVisibleToUsers,
    category: model.category,
    sortOrder: model.sortOrder,
    supportedTools: [...model.supportedTools],
    capabilities: { ...model.capabilities },
    supportsVision: model.supportsVision,
    supportsStreaming: model.supportsStreaming,
    envKeyName: model.envKeyName || providerEntry.envRequirements[0] || '',
    envRequirements: [...model.envRequirements],
    baseUrlResolver: model.baseUrlResolver || providerEntry.baseUrlResolver,
    regionSupport: [...model.regionSupport],
    supportedRegions: model.supportedRegions ? [...model.supportedRegions] : [...model.regionSupport],
    adminNotes: model.adminNotes,
    legacyAliases: model.legacyAliases ? [...model.legacyAliases] : undefined,

    toolCompatibility: [...model.supportedTools],
    routingPath: `${model.provider}/${model.capabilities.imageGeneration ? 'image' : model.capabilities.videoGeneration ? 'video' : model.capabilities.audioGeneration || model.capabilities.realtime ? 'audio' : model.capabilities.vision ? 'vision' : 'text'}`,
    promptTemplateGroup: model.capabilities.imageGeneration
      ? `${model.provider}-image`
      : model.capabilities.videoGeneration
        ? `${model.provider}-video`
        : model.capabilities.audioGeneration || model.capabilities.realtime
          ? `${model.provider}-audio`
          : model.capabilities.vision
            ? `${model.provider}-vision`
            : `${model.provider}-text`,

    supportsPreview: true,
    supportsExport: !model.capabilities.audioGeneration && !model.capabilities.videoGeneration,
    supportsPrint: !model.capabilities.audioGeneration && !model.capabilities.videoGeneration,
    supportsImageGeneration: model.capabilities.imageGeneration,
    supportsImageEditing: model.capabilities.imageEditing,
    supportsVideoGeneration: model.capabilities.videoGeneration,
    supportsAudioGeneration: model.capabilities.audioGeneration,
    supportsSpeechRecognition: model.capabilities.speechRecognition,
    supportsTranslation: model.capabilities.translation,
    supportsOCR: model.capabilities.ocr,
    supportsVisualReasoning: model.capabilities.vision,
    supportsTextReasoning: model.capabilities.reasoning,
    supportsLongContext: model.capabilities.longContext,
    supportsRealtime: model.capabilities.realtime,

    supportsText: model.capabilities.text,
    supportsFiles: model.capabilities.documentAnalysis || model.capabilities.vision,
    supportsDocumentAnalysis: model.capabilities.documentAnalysis,
    supportsQuizGeneration: model.capabilities.quiz,
    supportsGenerateContent: model.capabilities.text || model.capabilities.imageGeneration || model.capabilities.videoGeneration,
    supportsThinking: !!model.capabilities.thinking,
    supportsSearch: false,
    supportsInfographicWorkflows: model.capabilities.infographic,

    recommendedTools: [...model.supportedTools],
    badge: model.badge,
    priority: model.sortOrder,
  };
};

export const CANONICAL_MODEL_REGISTRY = CANONICAL_MODEL_DEFINITIONS.map((model) => Object.freeze({
  ...buildLegacyMetadata(model),
})) as readonly AIModelMetadata[];

export const MODEL_REGISTRY: AIModelMetadata[] = CANONICAL_MODEL_REGISTRY.map((model) => ({ ...model }));

export const USER_VISIBLE_MODEL_REGISTRY: AIModelMetadata[] = MODEL_REGISTRY
  .filter((model) => model.isEnabled !== false)
  .filter((model) => model.isVisibleToUsers !== false)
  .filter((model) => !['hidden', 'planned', 'disabled', 'deprecated'].includes(model.lifecycleStatus));

const MODEL_INDEX = new Map<string, AIModelMetadata>();
const MODEL_ALIAS_INDEX = new Map<string, string>();

for (const model of CANONICAL_MODEL_REGISTRY) {
  MODEL_INDEX.set(model.id, model);
  MODEL_INDEX.set(model.modelId, model);
  MODEL_ALIAS_INDEX.set(model.id, model.id);
  MODEL_ALIAS_INDEX.set(model.modelId, model.id);

  for (const alias of model.legacyAliases || []) {
    MODEL_ALIAS_INDEX.set(alias, model.id);
  }
}

export const getModelById = (id: string) => MODEL_INDEX.get(id);

export const getModelsByProvider = (provider: string) =>
  MODEL_REGISTRY.filter((model) => model.provider === provider);

/**
 * Resolves a model by either canonical id, provider modelId, or a persisted legacy alias.
 */
export const getModelByAnyId = (idOrModelId: string) => {
  const normalized = String(idOrModelId || '').trim();
  if (!normalized) return undefined;
  const canonicalId = MODEL_ALIAS_INDEX.get(normalized) || normalized;
  return MODEL_INDEX.get(canonicalId);
};

/**
 * Returns the canonical registry id when callers pass modelId aliases.
 */
export const toCanonicalModelId = (idOrModelId: string) =>
  getModelByAnyId(idOrModelId)?.id ?? idOrModelId;

export const getRegistrySortOrder = (idOrModelId: string) =>
  getModelByAnyId(idOrModelId)?.sortOrder ?? Number.MAX_SAFE_INTEGER;

export const sortModelsByRegistryOrder = <T extends { id: string }>(models: T[]): T[] =>
  [...models].sort((left, right) => {
    const orderDelta = getRegistrySortOrder(left.id) - getRegistrySortOrder(right.id);
    if (orderDelta !== 0) return orderDelta;
    return left.id.localeCompare(right.id);
  });
